apiVersion: v1
kind: Service
metadata:
  name: hello-php
spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    app: hello
---
apiVersion: v1
kind: Service
metadata:
  name: hello-node
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: hello
